#!/usr/bin/env python3
"""Split each authored fingertip hull into a 1 mm inner pad and outer shell.

Run with usd-core, numpy and scipy installed. Source STL files stay unchanged.
"""

from pathlib import Path

import numpy as np
from scipy.spatial import ConvexHull
from pxr import Usd, UsdGeom, UsdPhysics

from validate_gripper_collisions import stl_points

ROOT = Path(__file__).resolve().parent.parent
PAD_THICKNESS = 0.001


def split_hull(points, axis_sign):
    points = np.unique(points, axis=0)
    hull = ConvexHull(points)
    surface = max(points[:, 1] * axis_sign)
    distance = points[:, 1] * axis_sign - (surface - PAD_THICKNESS)
    crossings = []
    for face in hull.simplices:
        for a, b in zip(face, np.roll(face, 1)):
            if distance[a] * distance[b] < 0:
                t = distance[a] / (distance[a] - distance[b])
                crossings.append(points[a] + t * (points[b] - points[a]))
    return [
        np.unique(np.vstack((points[mask], crossings)), axis=0)
        for mask in (distance <= 0, distance >= 0)
    ]


def build():
    stage = Usd.Stage.CreateInMemory()
    UsdGeom.SetStageMetersPerUnit(stage, 1)
    UsdGeom.SetStageUpAxis(stage, "Z")
    for suffix, sign in (("", 1), ("_right", -1)):
        for i in (1, 2):
            name = f"link_3{suffix}_collision_{i:02}"
            source = ROOT / "meshes/collision/end_effectors/galbot_gripper" / f"link3{suffix}" / f"{name}.stl"
            for region, points in zip(("shell", "pad"), split_hull(stl_points(source), sign)):
                hull = ConvexHull(points)
                # Rebuild from only hull vertices to keep the USD compact.
                points = points[hull.vertices]
                hull = ConvexHull(points)
                faces = hull.simplices.copy()
                for face, equation in zip(faces, hull.equations):
                    a, b, c = points[face]
                    if np.dot(np.cross(b - a, c - a), equation[:3]) < 0:
                        face[1], face[2] = face[2], face[1]
                mesh = UsdGeom.Mesh.Define(stage, f"/{name}_{region}")
                mesh.CreatePointsAttr(points.tolist())
                mesh.CreateFaceVertexCountsAttr([3] * len(faces))
                mesh.CreateFaceVertexIndicesAttr(faces.flatten().tolist())
                mesh.CreateSubdivisionSchemeAttr("none")
                mesh.CreatePurposeAttr("guide")
                UsdPhysics.CollisionAPI.Apply(mesh.GetPrim())
                UsdPhysics.MeshCollisionAPI.Apply(mesh.GetPrim()).CreateApproximationAttr("convexHull")
    output = ROOT / "usd/payloads/finger_contact_regions.usda"
    stage.GetRootLayer().Export(str(output))
    output.write_text(output.read_text().rstrip().replace(
        "#usda 1.0", "#usda 1.0\n# Generated by scripts/build_finger_contact_regions.py; do not edit by hand."
    ) + "\n")


if __name__ == "__main__":
    build()
